workflows:
  maui-ios-simulator-build:
    name: Dotnet MAUI iOS Simulator
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      vars:
        DOTNET_PATH: $CM_BUILD_DIR/dotnet
        DOTNET: $CM_BUILD_DIR/dotnet/dotnet
        BUNDLE_ID: "io.codemagic.dtrdic15"
    scripts:
      - name: Install .NET SDK
        script: | 
          wget https://dot.net/v1/dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --install-dir $DOTNET_PATH
      - name: Install MAUI
        script: |
          $DOTNET nuget locals all --clear 
          $DOTNET workload install ios maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
      - name: Set Info.plist values
        script: | 
          PLIST=$CM_BUILD_DIR/Platforms/iOS/Info.plist
          PLIST_BUDDY=/usr/libexec/PlistBuddy
          $PLIST_BUDDY -c "Add :ITSAppUsesNonExemptEncryption bool false" $PLIST
      - name: CaliburnNuGet
        script: | 
          $DOTNET nuget add source https://www.myget.org/F/caliburn-micro-builds/api/v3/index.json --name CaliburnNuGet.org
      - name: workload list
        script: | 
          $DOTNET workload list
      - name: Build the app for iOS Simulator
        script: |
          $DOTNET publish -f net6.0-iossim \
            -c Release \
            -p:UseNet6=true \
            -p:ApplicationDisplayVersion="1.0.0" \
            -p:ApplicationVersion="1" \
            -p:RuntimeIdentifier=iossim \
            -o ../artifacts

    artifacts:
    - ./artifacts/*.app