workflows:
  maui-ios-simulator-build:
    name: Dotnet MAUI iOS Simulator
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      vars:
        DOTNET_PATH: $CM_BUILD_DIR/dotnet
        DOTNET: $CM_BUILD_DIR/dotnet/dotnet
        BUNDLE_ID: "io.codemagic.dtrdic15"
    scripts:
      - name: Install .NET SDK
        script: | 
          wget https://dot.net/v1/dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --channel 7.0 --install-dir $DOTNET_PATH
      - name: Install MAUI
        script: |
         $DOTNET_BIN nuget locals all --clear
         $DOTNET workload restore
         $DOTNET workload install maui-android maui-ios \
         --source https://aka.ms/dotnet7/nuget/index.json \
         --source https://api.nuget.org/v3/index.json
      # - name: Set Info.plist values
      #   script: | 
      #     PLIST=$CM_BUILD_DIR/Platforms/iOS/Info.plist
      #     PLIST_BUDDY=/usr/libexec/PlistBuddy
      #     $PLIST_BUDDY -c "Add :ITSAppUsesNonExemptEncryption bool false" $PLIST
      - name: CaliburnNuGet
        script: | 
          $DOTNET nuget add source https://www.myget.org/F/caliburn-micro-builds/api/v3/index.json --name CaliburnNuGet.org
      - name: workload list
        script: | 
          $DOTNET workload list
      - name: Build the app for iOS Simulator
        script: |
          $DOTNET build -f net7.0-ios -c Debug
    artifacts:
    - ./artifacts/*.app